name: EverythingPvP
version: 1.0
description: A PvP enchancement plugin!
author: Th3Gam3rz
main: com.th3gam3rz.everythingpvp.EverythingPvP
permissions:
  pvp.blood.see:
    description: Allows the player to see blood.
    default: true
  pvp.blood.change:
    description: Allows the player to change the blood color.
    default: op
  pvp.playerdrop.exempt:
    description: The player will not loose any money on death.
    default: op
  pvp.playerdrop:
    description: Allows the player to change the percentage of money dropped on death.
    default: op
commands:
  blood:
    description: Changes the blood color!
  playerdrop:
    description: Changes the percentage dropped on death!
